language: node_js
cache:
  directories:
    - node_modules # Speed up npm install
node_js:
  - "0.12.7"
  - "4.0.0"
  - "4.2.0"
  - "4.3.2"
  - "4.4.0"
  - "5.10.1"
  - "6.3.1"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
  - npm install -g gulpjs/gulp#4.0
  - cd project
  - npm install
script: gulp build_dist
