
# AppVeyor file
# http://www.appveyor.com/docs/lang/nodejs-iojs
# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 5.0.0
# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - npm cache clean
  - npm install -g gulpjs/gulp#4.0
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # run tests
  - cd project
  - gulp build_dist

# Don't actually build.
build: off

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules
